### ISSUE TITLE
Build scraper for data sources:

### ISSUE THREAD

**Issue by jkwening** [jkwening/bike-price-predictor#4]
- [x] Performance bike (scraper ready) **DONE #3 
- [x] Nashbar (next - similar structure as performance) **DONE  #7 
- [x] Competitive cyclist **DONE #14 
- [x] Wiggle #38 
- [x] LBSs with product information on their site
  - [x] Start local
  - [x] www.citybikes.com
  - [x] https://www.contebikes.com/product-list/bikes-1000/ (similar to citybikes.com)
  - [x] https://www.bicycleproshop.com/product-list/bikes-1000/ (similar to citybikes)
  - [x] spokes (https://www.spokesetc.com/product-list/bikes-1000/)
    - [ ] Cross US stores for diversity
- [x] REI (XHR - results: returns JSON -> results) #39 
- [x] Trek (https://www.trekbikes.com/us/en_US/bikes/c/B100/) --see bikes tab for categories
- [x] Specialized (https://www.specialized.com/us/en/shop/bikes/c/bikes)
  - [x] LBS (Erik's): https://www.eriksbikeshop.com/eriks-bicycle-buying-guide.aspx
- [x] Giant (https://www.giant-bicycles.com/us/bikes/startpage)
  - [x] LBS (FoxValley): http://www.giantfoxvalley.com/us/bikes
- [x] Canyon (https://www.canyon.com/en-us/)
  * Tricky website, will need a little more complex scraper
- [x] bicyclewarehouse (https://bicyclewarehouse.com/)
- [x] jenson bikes (https://www.jensonusa.com/Complete-Bikes)
- [ ] ~colarado cycles (https://www.coloradocyclist.com/bikes)~
- [ ] ~tree fort bikes (https://www.treefortbikes.com/cat/5/Bikes--and--Frames)~
- [ ] ~bike tires direct (https://www.biketiresdirect.com/bikes-frames-and-forks-category)~
- [ ] western bikes (https://www.westernbikeworks.com/complete-bikes)
- [ ] chain reaction (https://www.chainreactioncycles.com/us/en/bikes)
- [ ] ~bikes exchange (https://www.bikeexchange.com/)~ Used bikes retailer
- [ ] ~the house (https://www.the-house.com/bike-shop.html)~
- [ ] ~universal cycles (https://www.universalcycles.com/shopping/index.php?category=483)~
- [x] backcountry (https://www.backcountry.com/bikes-frames)
- [ ] ~https://www.incycle.com/~
- [x] titanium bike (list of brands: https://www.roadbikerider.com/titanium-bike-brand-list/)
  - [x] https://litespeed.com/pages/bikes
  - [x] https://lynskeyperformance.com/
  - [ ] https://airbornebicycles.com
  - [ ] ~https://sagetitanium.com/#~ single bike per bike type
- [ ] ~Walmart / Kmart / big chains~ **EXCLUDING - low end products
- [ ] ~Ebay  **EXCLUDING~ - off-brand bikes,...doesn't seem like good resource for standard bike purchases

NOTE: resource for other online bike stores: https://intheknowcycling.com/2018/07/23/online-bike-store-rankings/

**Comment by jkwening** [comment]
Notes for LBS-Erik's Site:

Bike Categories:
1. div -> class='GBucketCont'
2. div -> class='GBucket'
    * h2 _> contents: category name
    * a -> href: link to category product listing

Product Listing page:
* defaults to 30 items per page
* view options: 30/60/90
* Get number of products:
  1. div -> class='searchHeadingInfo'
  2. h1 -> class='SearchHeading'
  3. span with long id
  4. span -> contents with string: '# Results for'
* Get products listings
  1. div -> class='SearchProductList'
  2. div -> id='Td2' (contains each product)
  3. div -> class='DeptProdText'
      * a: href = spec link, 'rapi' = prod_id, span -> class='NameLabel' = description
      * span -> id='mainSiteContent_MainContent_SearchView_ProductList1_PricingControl2_0_PricingControl_0' **Not useful**
        * span -> span class='SalePriceA' -> span -> contents: price  **Current price**
        * div -> span class='MSRPPriceA' -> span -> contents: price **Only If on Sale**
* Brand will need to be parsed from description - first

**Comment by jkwening** [comment]
Scraped 20+ sites, so moving onto munging, EDA, and model building phase now.
